# Generated by Django 4.2 on 2023-05-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_almacen',
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tablaventas',
            name='ganancias',
            field=models.DecimalField(decimal_places=2, max_digits=500),
        ),
        migrations.AlterField(
            model_name='tablaventas',
            name='precio_total_compra',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tablaventas',
            name='precio_total_venta',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
