# Generated by Django 4.2 on 2023-05-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_remove_customuser_contraseña_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='cantidad_producto_vendidos',
            field=models.IntegerField(default=0),
        ),
    ]
