# Generated by Django 4.2 on 2023-06-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_almacen_cantidad_producto_vendidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
